title: CakePHP Brasil
email: contato@cakephpbrasil.com.br
copyright_name: CakePHP Brasil
description: "CakePHP Brasil é uma comunidade de desenvolvedores apaixonados pelo framework PHP de desenvolvimento rápido."
url: "http://cakephpbrasil.com.br"
header-img: assets/img/home-bg.jpg
baseurl: ""
github_username:  CakePHPBrasil
email_username:  contato@cakephpbrasil.com.br
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","README.md"]
gems: [jekyll-paginate]
